export default {
  auth: {
    auth_email_sent: false,
    isLoadingReset: true,
    password_reset: false,
    redirect_page: false,
  },
  patient: {
    currentWidget: 'settings',
    clientID: 0,
    flag: 2,
    entities_list: [],
    transaction_list: {list:[], type: [], assignment_type: {}},
    clientsData: [],
    clientsLoading: false,
    customersData: {
      'employee': [],
      'ownership': [],
      'merger': [],
      'security': [],
      'other': []
    },
    entites_update_message: '',
    settingText: 'Settings',
    record_item: null,
    customersLoading: false,
    treeCompanySelected: undefined,
    main_company_selected_name: '',
    searchCompaniesSelected: [],
    customersNamesCollections: [],
    customersNameCollectionsLoading: false,
    selectedRFID: '',
    customersRFIDAssets: [],
    customersRFIDAssetsLoading: false,
    lawyerList:[],
    lawyerListLoading: false,
    documentList: [],
    documentListLoading: false,
    update_document_row: null,
    childCompanies: [],
    companiesList: [],
    companyListLoading: false,
    userList: [],
    userListLoading: true,
    recordItems: {},
    recordItemsLoading: false,
    treeToggle: [],
    treeExpand: [], 
    errorItems: {count:{uspto: 0, patent: 0}, list:{invent: [], assign: [], corr: [], address: [], security: []}},
    errorItemsLoading: false,
    searchCompanies: [],
    searchCompanyLoading: false,
    alertsCount: 0,
    messagesCount: 0,
    charts: {},
    chartsLoading: false,
    timeLine: {},
    timeLineLoading: false,
    transactions: {buy: 0, sale: 0, security: 0, release: 0, license_in: 0, license_out: 0},
    transactionsLoading: false,
    comments: '',
    commentsLoading: false,
    screenHeight: 0,
    screenWidth: 0,
    assets: {},
    assetsLoading: false,
    assetsOutsource: {},
    assetsOutsourceLoading: false,
    validateCounter: {application: 0, patent: 0, encumbered: 0},
    validateCounterLoading: false,
    assetsCount: {weekly_transactions: 0, weekly_applications: 0, monthly_transactions: 0, montly_applications: 0, quaterly_transactions: 0, quaterly_applications: 0},
    assetsCountLoading: false,
    main_company_selected: false,
    tree: {}, 
    company_tree: {},
    currentAsset: '',
    currentAssetType: '',
    commentMessage: '',
    siteLogo: {},
    nestGridTab: 0,
    chartTab: 0,
    timelineTab: 0,
    fixitTab: 0,
    recorditTab: 0,
    pdfTab: 0,
    settingTab: 0,
    chart_one: [],
    chart_two: [],
    chart_three: [],
    chart_four: [], 
    chart_five: [], 
    add_years: true,
    errorTotal: 0,
    illustrationUrl: 'about:blank',
    curTree: [
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      }
    ],
  }
};